### ISSUE TITLE
Sometimes places adjacent doors

### ISSUE THREAD

**Issue by munificent** [munificent/hauberk#14]
I just found a room (in the training area level 1) that has an entrance of 2 doors and an opening. I assume the 'choose connections' phase of your algorithm isn't checking to see if there is already a connection used next to it beforehand? IE:

``` text
#.####
#.#
#.#
#.'
#.'
#. .
#.###
#.#
#.#
```

**Comment by seanohue** [comment]
Could be some fancy double doors.

**Comment by munificent** [comment]
:door: :door: :grin:

**Comment by munificent** [comment]
Totally rewrote the dungeon generator, so this should be fixed now.
