### ISSUE TITLE
I was killed by a {1}

### ISSUE THREAD

**Issue by abunner** [munificent/hauberk#20]
![screen shot 2015-02-16 at 2 48 43 pm](https://cloud.githubusercontent.com/assets/489841/6220442/27283d78-b5eb-11e4-932a-04d97af7c7d8.png)

I made it to the Goblin Stronghold, engaged a slug in mortal combat and then was killed by a {1}.

I checked the Javascript console and just saw:
Saved. /hauberk/main.dart.js:5518

This is Mac Chrome Version 40.0.2214.111 (64-bit)

Prior to this fight-to-the-death with a slug, I tried clicking on the font-changing buttons a bunch.

**Comment by abunner** [comment]
Correction: Actually I died in the Training Grounds Level 1, not the Goblin Stronghold.

**Comment by munificent** [comment]
Nice catch! If you were killed by something indirect (in this case poison, but missile attacks had the same problem), then it wouldn't know the attacker that killed you. Fixed now (though I haven't pushed a new build to gh-pages yet).
