### ISSUE TITLE
Spawned in a single tile space and can't move.

### ISSUE THREAD

**Issue by richrd** [munificent/hauberk#23]
This happened to me today:

![hauberk-wall-bug](https://cloud.githubusercontent.com/assets/3417292/16014591/799709fa-319a-11e6-9f4d-311adc7a7f94.png)

**Comment by munificent** [comment]
Walk diagonally. :) `p`

**Comment by richrd** [comment]
Doh! I feel stupid for not trying that even though I knew I diagonal movement was possible... Must be my lack of sleep :P
