### ISSUE TITLE
Can't get to hero screen

### ISSUE THREAD

**Issue by richrd** [munificent/hauberk#29]
After I created my hero, I was able to get to the hero screen, but after playing for a while I can no longer access it.

Now when I select my hero I just get presented with the level selector. Am I missing something or is this a bug?

**Comment by richrd** [comment]
Ok, I get it now :)
https://github.com/munificent/hauberk/blob/92f157e3af94e1a22fd21bead063a6cd7949936f/lib/src/ui/select_depth_screen.dart#L54

Would you want some help writing docs for stuff? I didn't even know about skills before reading through the code. I was playing without that feature and it felt pretty hard.

**Comment by munificent** [comment]
> Would you want some help writing docs for stuff?

At some point, maybe, but the game is in heavy flux right now — lots of stuff broken, constantly trying new things out, etc. — so that would probably be painful and unrewarding. Hauberk, for better or worse, isn't in a great state for contributions. :-/
