### ISSUE TITLE
precompiler errors 

### ISSUE THREAD

**Issue by lordkuragari** [munificent/hauberk#36]
Failed to precompile markdown:markdown:
file:///Users/t-justinl/.pub-cache/hosted/pub.dartlang.org/markdown-2.0.0/lib/src/util.dart:6:37: Error: Getter not found: 'ELEMENT'.
    const HtmlEscape(HtmlEscapeMode.ELEMENT).convert(html);
                                    ^
Failed to precompile build_runner:build_runner:
file:///Users/t-justinl/.pub-cache/hosted/pub.dartlang.org/io-0.3.2+1/lib/src/shared_stdin.dart:55:22: Error: Getter not found: 'UTF8'.
    return transform(UTF8.decoder).transform(const LineSplitter());
                     ^^^^
file:///Users/t-justinl/.pub-cache/hosted/pub.dartlang.org/io-0.3.2+1/lib/src/shared_stdin.dart:55:22: Error: The getter 'UTF8' isn't defined for the class '#lib1::SharedStdIn'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'UTF8'.
    return transform(UTF8.decoder).transform(const LineSplitter());
                     ^
make: *** [serve] Error 1

installed dart today and havent changed anything

**Comment by munificent** [comment]
Which version of Dart did you install? You'll want one of the newer dev versions (2.0.0-dev...), not the latest stable version (1.24).

**Comment by pk2016** [comment]
me too:
Failed to precompile markdown:markdown:
file:///C:/Users/Reytine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/markdown-2.0.0/lib/src/util.dart:6:37: Error: Getter not found: 'ELEMENT'.
    const HtmlEscape(HtmlEscapeMode.ELEMENT).convert(html);
                                    ^
Failed to precompile build_runner:build_runner:
file:///C:/Users/Reytine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/io-0.3.2+1/lib/src/shared_stdin.dart:55:22: Error: Getter not found: 'UTF8'.
    return transform(UTF8.decoder).transform(const LineSplitter());
                     ^^^^
file:///C:/Users/Reytine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/io-0.3.2+1/lib/src/shared_stdin.da
rt:55:22: Error: The getter 'UTF8' isn't defined for the class '#lib1::SharedStdIn'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'UTF8'.
    return transform(UTF8.decoder).transform(const LineSplitter());


win10 64  2.0.0-dev.69.4

**Comment by munificent** [comment]
I just updated the dependencies. At least with the latest bleeding edge Dart SDK (which is what I tend to use because I'm on the Dart team) it's working now.
