### ISSUE TITLE
Casting the spell "Icicle" on yourself.

### ISSUE THREAD

**Issue by groothecommenter** [munificent/hauberk#38]
Casting the spell "Icicle" on yourself will cause the spell animation to endlessly repeat, preventing you from issuing any commands.

I am playing the game through my default browser (Firefox), and I've not yet tested anything on but my local machine.

Probably best to not ask why I was casting offensive spells against myself.

I'm really enjoying your game so far, with a long history of classical roguelikes under my belt I can readily feel the thought and care in the code.  I hope things go well for you and you continue to have time to work on it.  If this comment helps to bring any fixes or additions to your work, I'm glad it helped and was worth your time.

**Comment by munificent** [comment]
Hahaha, oops, yes! The LOS code that walks the line is getting stuck in an infinite loop since the direction vector is zero. It should check for that case and prevent it from happening. :)
