### ISSUE TITLE
Manual Aiming of Spells

### ISSUE THREAD

**Issue by nbystrom** [munificent/hauberk#40]
With some spells, particularly Fire Barrier and Brilliant Beam, I occasionally find myself wanting to manually aim the spell, so that I can put my barrier down exactly where I want it, or maximize the number of enemies hit by Brilliant Beam's cone. Perhaps the auto-aim could be replaced with a hybrid aim where the reticle auto-aims, but the player can then toggle that off if they want to manually aim their spell?

**Comment by munificent** [comment]
> Perhaps the auto-aim could be replaced with a hybrid aim where the reticle auto-aims, but the player can then toggle that off if they want to manually aim their spell?

If you hit tab while the target dialog is up, it switches between "target monster" and "target floor" mode. In the latter, you can move around and target any point you want. :)
