### ISSUE TITLE
blackout.

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#43]
I have run across this glitch about 3 or four times,
I will light a candle in a dark room, and I have a 
bunch of other light sources in my inventory. 
(lamps, tallow candles, wax candles, torches.)
Nothing unusual happens until I get to the next floor,
That's when all of my light sources just vanish from my inventory.  : (

**Comment by munificent** [comment]
Strange! This only happens after using a light source item?

**Comment by En810** [comment]
YEP, I only started seeing this after the last update. 
I'm assuming that lights last a certain amount of time
and then exhaust,  it seems like the timer is doing some 
bad math between levels.

**Comment by En810** [comment]
I wonder if I might be loosing them to environmental fire effects with out realizing it? :/

**Comment by munificent** [comment]
Yes, light sources can burn up if you are hit with fire attacks or walk on burning tiles.
