### ISSUE TITLE
The browser version of the game fails to load.

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#44]
Starting around the middle of last week...
the browser version of the game fails to load.
(I tried 4 different browsers)

"ERROR
Service Unavailable
The requested service is unavailable.
Please try again later. "

**Comment by En810** [comment]
Thanks, it seems to be working now for some reason. :)

**Comment by munificent** [comment]
Probably the [massive GitHub outage](https://blog.github.com/2018-10-30-oct21-post-incident-analysis/).
