### ISSUE TITLE
Several bugs and limits issues

### ISSUE THREAD

**Issue by StormWingDelta** [munificent/hauberk#45]
First you can't get items out of your home, not sure what the trigger is since I come at one time but hitting G while it gets into the right menu doesn't let me pull anything.

Second the bow's cost is way too high! lose a digit at least please so it'll come down into a usable range.

Third Shops fill up with sold items and either don't sell them between levels or for a long time. Also shops can fill up with their own items after a while. maybe they shops should use a scrolling menu to get around this.

Forth the inventory stops at x and doesn't go to z pretty sure just by guessing it's an off by one or two error or they just aren't included.

Nice game though. :)

**Comment by En810** [comment]
I didn't think the shop was implemented yet ? :/

**Comment by munificent** [comment]
Thanks for the feedback! I just re-added shops so a bunch of issues aren't too surprising. I'll try to fix those bugs when I get a chance.
