### ISSUE TITLE
Character creation bugs

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#46]
The first bug occurs when you create a new character, 
as the [enter] key doesn't take you back to the menu after you are done.
I hit [esc] instead and got back to the main menu and realized I had made several characters.
so the character creation works but it's missing a link to take you back.

The second and more pressing error, is that my new characters don't seem to be saving.
the second I close the browser, they are just gone. even if I complete several levels. :/

Ps. My older characters are still there but they don't seem to work well with the new content.
 the newer of the 2 old characters don't save any new progress.

**Comment by munificent** [comment]
Oof. :(

Can you open the developer console while you're playing and see if you get any errors in there? If so, stick them in a comment here and I'll take a look.

**Comment by En810** [comment]
Looks lit it might be a problem with Microsoft edge, I just got it to work normally on internet explorer.

**Comment by En810** [comment]
yay, looks like you fixed it. :)

Ps. I like the new score screen after you complete a level.

**Comment by munificent** [comment]
:D
