### ISSUE TITLE
Character stats button ?

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#48]
Is there a screen/menu/button to show my characters strength, intelligence, dexterity, etc..?
I have been trying to find it for a while now.

**Comment by munificent** [comment]
The main stats are visible on the right side of the screen. You can get to some additional info by pressing A ("about") and then skills under Shift+S. This is something that could definitely be improved. I find the current state of the hero pretty opaque right now, and it's something I'd like to make progress on.

**Comment by En810** [comment]
Doh I can't believe I missed that.
