### ISSUE TITLE
how to play...? (Hauberk main screen MISSING)

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#49]
I'm only seeing "How to play" on the Hauberk main screen, everything else is missing.
different browsers made no difference.

**Comment by munificent** [comment]
Oops, I broke it with this commit: https://github.com/munificent/hauberk/commit/753d1cb182b3ef5d892a20374e4eef8e37e870cb

I'll try to get a fix out soon.

**Comment by munificent** [comment]
Should be fixed now.
