### ISSUE TITLE
Stuck in town.

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#50]
There seems to be a glitch when exiting the new buildings or dungeon your character gets stuck in the doorway after pressing [Eec]. 
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, http://download.microsoft.com/download/B/9/F/B9FF9327-7A72-4165-BF91-9B7EEB6C579B/DeviceList.json
26

Also the dungeon load screen hangs as well. :(

SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, http://download.microsoft.com/download/B/9/F/B9FF9327-7A72-4165-BF91-9B7EEB6C579B/DeviceList.json
15

**Comment by En810** [comment]
Seems to be working now. 
Thanks for your hard work.

**Comment by munificent** [comment]
Ah, yes, meant to update this bug. :)
