### ISSUE TITLE
Can't Use things

### ISSUE THREAD

**Issue by En810** [munificent/hauberk#51]
I don't seem to be able to equip things,
as the options is blacked out.
am I missing a new feature or something ?

**Comment by En810** [comment]
Ok, looks like I have to use "e" instead of "u" to equip stuff now.
Ps, The dual wielding seems to be working. :)

**Comment by munificent** [comment]
Yes, I really need docs. :)

Equipping is a separate keypress because now there are items (light sources) which can be both equipped or consumed.

**Comment by En810** [comment]
Oh that reminds me what's the difference between a torch in your inventory vs a torch in your hand ?
is it like double the light or something and will it burn out ?

**Comment by munificent** [comment]
A torch in your inventory doesn't do anything any more. Now to have it give the hero emanation, you need to equip it.
