### ISSUE TITLE
my character is gone

### ISSUE THREAD

**Issue by krux02** [munificent/hauberk#55]
I wanted to play again. This morning everything was fine. Now the character is gone. I think I was level 15 warrior and dungeon 47 or something like that. Can't remember precisely. But now it is just gone and I can't play anymore.

**Comment by Mudshovel** [comment]
Hey there,

Not sure if this will help you. But your "save game" is in your browser's local storage.

Might wanna check over there if there's something wrong or if you cleared your cache 😀

**Comment by krux02** [comment]
well I have some on and off experience with hauberk. My character was there again with no particular reason and I continued playing. Then I wanted to play again and it was gone and now it is there again. I can't really tell what the reason for this weird behavior is. I certainly don't feel very secure with this status.

**Comment by krux02** [comment]
This experience of a character that just disappears and then reappears for no particular reason continues. I don't understand the reason for it. I also only use a single browser, so that can't be the cause of it.

**Comment by johnalexhebert** [comment]
Which browser and OS are you using? How are you starting the game?

**Comment by krux02** [comment]
I use chromium on Manjaro Linux. I start the game with the link http://munificent.github.io/hauberk nothing else.

**Comment by munificent** [comment]
Aww, I'm sorry about that. Hauberk is nowhere near a stable state—vast swathes of the game are completely unimplemented—so there is unfortunately no expectation of stability. :(

**Comment by krux02** [comment]
sorry to hear that. I like hauberk because of it's simplicity and the style. But I ran into a few crashes as well. I know the project is unfinished, but here is some feedback to the game if you want it:

Good:
 * The graphics are great. I really enjoy this reduced one bit sprites (1 color and transparent layer).
 * The simplicity is great. I feel overwhelmed by nethack or adom where that are tons of skills that I have no idea what they are good for.

Not so good:
 * I am classified as a warrior. Still I am always to weak to wear anything that I would associate with a warrior: Heavy armore and weapons. Even though I find these weapons all the time, I just end up using a magic dagger or a spear and elven armor.
* Food is everywhere, so muclh even that at some point I stopped picking it up and steated eating from the floor whenever I felt hungry. This became tedious. Maybe when food supply isn't supposed to be a challenge it should be removed as a mechanic. Or the food (especially the stale bisquits) should be eaten automatically when stepping on them. Other foods were completely unnecessary.
* During the later game, items found on the floor did not progress with the monsters.


Anyway overall it was a very fun experience. And I played it while listening to the dungeon master 2 soundtrack. I think it really fits the atmosphere pretty well.

**Comment by munificent** [comment]
Thank you for the feedback, that's definitely helpful. :)
