### ISSUE TITLE
How can I craft things?

### ISSUE THREAD

**Issue by Lynx-Rynn** [munificent/hauberk#68]
I tried to press `H` in town but nothing happened. I can't find the crucible in my home either.
![image](https://github.com/user-attachments/assets/5fae3a98-f818-4461-93e6-3454bade7b6b)

**Comment by munificent** [comment]
I think the crucible is currently unavailable. I had it working for a while but then was exploring a different game design that wasn't based around crafting. The code is still there (and I do think I want to bring crafting back), but it's not accessible to players.
